name: Sync with Azure DevOps

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Sync with Azure DevOps
        env:
          AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
          AZURE_DEVOPS_REPO: https://dev.azure.com/seth2958/_git/Bain%20Commercial%20Dashboard
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: github-actions[bot]@users.noreply.github.com
        run: |
          git remote add azure https://${AZURE_DEVOPS_PAT}@dev.azure.com/seth2958/_git/Bain%20Commercial%20Dashboard
          git fetch azure
          git merge --allow-unrelated-histories azure/main
          git push azure main
